In [1]:
import numpy as np
import pandas as pd

In [2]:
# Upload DataFrame

df = pd.read_csv('data\diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:
# First i mixing data in the DataFrame

df = df.sample(frac=1)
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
155            7      152             88             44        0  50.0   
386            5      116             74             29        0  32.3   
159           17      163             72             41      114  40.9   
302            5       77             82             41       42  35.8   
729            2       92             52              0        0  30.1   
..           ...      ...            ...            ...      ...   ...   
174            2       75             64             24       55  29.7   
161            7      102             74             40      105  37.2   
173            1       79             60             42       48  43.5   
572            3      111             58             31       44  29.5   
0              6      148             72             35        0  33.6   

     DiabetesPedigreeFunction  Age  Outcome  
155                     0.337   36        1  
386                     0.660   35        1  
159                     0.817   47        1  
302                     0.156   35        0  
729                     0.141   22        0  
..                        ...  ...      ...  
174                     0.370   33        0  
161                     0.204   45        0  
173                     0.678   23        0  
572                     0.430   22        0  
0                       0.627   50        1  

[768 rows x 9 columns]

In [4]:
# Convert Dataframe into numpy arrays

X = df.drop(['Outcome'], axis=1).values
y = df['Outcome'].values

In [5]:
X

array([[  7.   , 152.   ,  88.   , ...,  50.   ,   0.337,  36.   ],
       [  5.   , 116.   ,  74.   , ...,  32.3  ,   0.66 ,  35.   ],
       [ 17.   , 163.   ,  72.   , ...,  40.9  ,   0.817,  47.   ],
       ...,
       [  1.   ,  79.   ,  60.   , ...,  43.5  ,   0.678,  23.   ],
       [  3.   , 111.   ,  58.   , ...,  29.5  ,   0.43 ,  22.   ],
       [  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ]])

In [6]:
y

array([1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,

In [7]:
# Import from sklearn functions we need for ML.

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [8]:
# Split our data into train and test sets.

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42) 

In [9]:
# Build model on the train data.

knn = KNeighborsClassifier()

In [10]:
# Train the model.

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [11]:
# Use predict function to make predictions.

y_pred = knn.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [12]:
# Now i can chek accuracy of my model by using accuracy score to find how good model.

accuracy_score(y_pred, y_test)

0.6875

`I have got a 68%, is not the best result.`

`We can improve our result. For this i'll try to use Standard Scaler function.`

In [13]:
# Import from sklearn StandardScaler function.

from sklearn.preprocessing import StandardScaler

In [14]:
# Create Standard Scaler model.

std = StandardScaler()
X_train_scale = std.fit_transform(X_train)
X_test_scale = std.transform(X_test)

In [15]:
# Check minimum value.

np.min(X_train_scale)

-4.120851558392117

In [16]:
# Check maximum value.

np.max(X_train_scale)

7.017978160871017

In [17]:
# Now i'm going to use this scaled values to train our model

knn = KNeighborsClassifier()
knn.fit(X_train_scale, y_train)

KNeighborsClassifier()

In [18]:
# Use predict function to make predictions.

y_pred = knn.predict(X_test_scale)

In [19]:
# Check the accuracy score.

accuracy_score(y_pred, y_test)

0.7135416666666666

`After using the Standard Scaler functiom, I have got a 71%, this result better but not the best result i can obtain.`

`I'm going to improve result using Correlation. For this i'm going to use PointBiserial Correlation from kydavra library.`

In [20]:
# From library Kydavra importing the PointBiserialCorrSelector method.

from kydavra import PointBiserialCorrSelector

`PointBiserial Correlation allow to select the most important columns.`

In [21]:
point = PointBiserialCorrSelector()
selected_cols = point.select(df, 'Outcome')

In [22]:
# Checking the selected columns.

selected_cols

['Glucose', 'Pregnancies', 'BMI', 'Age']

In [23]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [24]:
X = df[selected_cols].values
y = df['Outcome'].values

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [26]:
std = StandardScaler()
X_train_scale = std.fit_transform(X_train)
X_test_scale = std.transform(X_test)

In [27]:
 knn.fit(X_train_scale, y_train)

KNeighborsClassifier()

In [28]:
y_pred = knn.predict(X_test_scale)

In [29]:
accuracy_score(y_test, y_pred)

0.7395833333333334

`After using PointBiserial Correlation i improve my result umtil 74%.`

`In sklearn we can set the best hyperparameters to create the best model. First we have to define hyperparameters library.`

In [30]:
parameters = {
    'n_neighbors' : range(1, 20, 2),
    'p' : range(1, 5),
    'metric' : ['euclidean', 'manhattan', 'chebyshev', 'minkowski']
}

In [31]:
# Import from sklearn GridSearchCV function

from sklearn.model_selection import GridSearchCV

In [32]:
grid = GridSearchCV(knn, parameters)

In [33]:
grid.fit(X_train_scale, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan', 'chebyshev',
                                    'minkowski'],
                         'n_neighbors': range(1, 20, 2), 'p': range(1, 5)})

In [34]:
grid.best_estimator_

KNeighborsClassifier(metric='manhattan', n_neighbors=17, p=1)

`I have got next result: the best estimator is the KNN algoritm with metric - "manhattan" and n_neighors = 17.`

In [35]:
best_knn = grid.best_estimator_

In [36]:
id(best_knn)

1215473152496

In [37]:
id(grid.best_estimator_)

1215473152496

In [38]:
grid.best_score_

0.7638380809595202

`The best accuracy score is 76%.`